### ISSUE TITLE
Unable to report for greater than 200 classes

### ISSUE THREAD

**Issue by roby-handinhand** [forcedotcom/ApexUnit#61]
Currently ApexUnit submits the specified test classes to the org and returns a single parent job Id. Async Apex jobs have a max of 200 apex classes, which means when ApexUnit submits >200 classes, those are submitted as multiple async jobs. ApexUnit only returns 1 job Id, so it only reports on the results of the 200 classes submitted as part of the first job. The rest of the tests are actually executed in the org, but ApexUnit is not tracking or reporting on them.

**Comment by vamshi-sfdc** [comment]
@adarsh-ramakrishna-sfdc can you please confirm this limitation on the reporting module?

**Comment by adarshramakrishna** [comment]
I have seen this question before as well. https://github.com/forcedotcom/ApexUnit/issues/41 . Since the user did not follow up with us, we weren't sure if it was related to multiple namespaces in use. Now that we have this bug, Seems like the test execution batch can only take in 200 tests at a time. We need to test this out. We might need to look into the option of creating multiple batches of 200 tests each.

**Comment by robymathew** [comment]
If it helps, I created a fork of ApexUnit that submits classes in batches of 200 (if there are >200 classes). I don't think it's ideal though since it submits these jobs synchronously - I think this can be done async: https://github.com/robymathew/ApexUnit

**Comment by adarshramakrishna** [comment]
Thanks @roby-handinhand . Can you please point us to the commit ?

**Comment by robymathew** [comment]
Sure, this is the fix. 

https://github.com/robymathew/ApexUnit/commit/4682a4d735a08848cffb7a1f2e585f763120b14d#diff-854284a1d1b65757ef0a9dc16c1a442fL23

I added a couple of commits after to address reporting and logging. Here are all the commits:

https://github.com/robymathew/ApexUnit/commits/batchFix

**Comment by vamshi-g** [comment]
@adarshramakrishna what are the next steps to close the loop on this? If you do not wish to look into this please share the same

**Comment by adarshramakrishna** [comment]
@vamshi-g We can have a PR for this and go from there. I have put in few comments for robymathew's commit. You have any other approach in mind? 
@robymathew   can you please create a PR with your commit for this issue?

**Comment by vamshi-sfdc** [comment]
@Adarsh: are you waiting for PR initiation or modifications on a current t
PR?

On Jun 15, 2017 8:09 AM, "Adarsh" <notifications@github.com> wrote:

@vamshi-g <https://github.com/vamshi-g> We can have a PR for this and go
from there. I have put in few comments for robymathew's commit. You have
any other approach in mind?
@robymathew <https://github.com/robymathew> can you please create a PR with
your commit for this issue?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/forcedotcom/ApexUnit/issues/61#issuecomment-308766321>,
or mute the thread

**Comment by adarshramakrishna** [comment]
@vamshi-g  we do not have a PR for this yet in https://github.com/forcedotcom/ApexUnit/pulls 
robymathew has modified the code in this fork of the project. We need a new PR for this

**Comment by roby-handinhand** [comment]
Hey @adarshramakrishna - this was fixed a while back in the ApexUnit repo by @rduvvarapu - it looks like he took the gist of my fix and used it to create a fix in master.

Here's the commit:
https://github.com/forcedotcom/ApexUnit/commit/e63ff5d420e6831892737423154df6e594c2ec1c

**Comment by dragon0556** [comment]
This issue is fixed.
