### ISSUE TITLE
"Request-URI Too Long" error when calculating code coverage

### ISSUE THREAD

**Issue by roby-handinhand** [forcedotcom/ApexUnit#62]
I am running into this error when ApexUnit is trying to calculate the cove coverage from the manifest file specified. I'm assuming it's because we have 100's of classes in the manifest file. Here's a snippet from the log:

[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.fileReader.ApexManifestFileReader - Reading from Manifest files: sourceClasses.txt
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.fileReader.ApexManifestFileReader - Reading Manifest file from location : sourceClasses.txt
Mar 13, 2017 8:48:06 PM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.codeCoverage.WebServiceInvoker - Status code : 414   Status message from the get request:Request-URI Too Long Reason phrase: Request-URI Too Long
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Code coverage metrics not computed. Null object returned while processing the JSON response from the Tooling API
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit

**Comment by alexiswilliams** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I will setup a meeting with you to get details about the job running the build and depot. 


Sent from Yahoo Mail for iPhone


On Monday, March 13, 2017, 7:01 PM, roby-handinhand <notifications@github.com> wrote:


I am running into this error when ApexUnit is trying to calculate the cove coverage from the manifest file specified. I'm assuming it's because we have 100's of classes in the manifest file. Here's a snippet from the log:

[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.fileReader.ApexManifestFileReader - Reading from Manifest files: sourceClasses.txt
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.fileReader.ApexManifestFileReader - Reading Manifest file from location : sourceClasses.txt
Mar 13, 2017 8:48:06 PM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.codeCoverage.WebServiceInvoker - Status code : 414 Status message from the get request:Request-URI Too Long Reason phrase: Request-URI Too Long
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Code coverage metrics not computed. Null object returned while processing the JSON response from the Tooling API
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit

**Comment by vamshi-g** [comment]
@alexiswilliams is this triaged?

**Comment by awillia2** [comment]
Yes, we have a bug to track this issue internally.

**Comment by roby-handinhand** [comment]
FYI @awillia2 - I committed a fix for this to my fork of the repo here if you'd like to have a look, I simply batched up classes into groups of 100 (if there were > 100) for code coverage queries.

https://github.com/robymathew/ApexUnit/commit/12fc46cf63b8408cb493151f75bab1c898f3d9c4

Thanks,
Roby

**Comment by dragon0556** [comment]
This issue is fixed.
